### ISSUE TITLE
Something odd

### ISSUE THREAD

**Issue by emilorol** [ianrogren/jquery-backDetect#2]
Thank you for this library.

If I trigger an alert the page will stay still until I close the alert, but if I use a bootstrap model it will take a second (I am not using the delay option) or two after showing the modal and it will go back to the previews page.

What am I missing?

**Comment by ianrogren** [comment]
Hi Emil,

Thanks for your interest in this library.  So there are two things here:

The delay is use to trigger when the browser should start detecting when the back button is clicked.  This is to prevent people from triggering the back detect if they are spamming the back button if that is what you are trying to do.

In regard to the bootstrap modal, I do see it firing if I do add something like:
```
        $(window).load(function(){
          $('body').backDetect(function(){
            $('#exampleModal').modal('show');
          });
        });
```
However, it will disappear before the browser actually goes back one page.  The problem is that there is no override for actually delaying or stopping the browser back button action.   There are ways to get around to put in overrides, but it can be messy to try and change default browser behavior.  I'd say look into window.history.pushState, onpopstate and hash to see if something there might meet your needs.

An alternative to putting in an override would be to use the [window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).  This is what I originally created this library for so I can pass variables through the localStorage and read them after someone hits the back button.  This way you can trigger the modal to fire after the page has reloaded once someone hits the back button.

I hope that helps, let me know if you have any other questions.

Ian

**Comment by emilorol** [comment]
I was able to solved the issue adding something like this:

```js
    var history_api = typeof history.pushState !== 'undefined';
    if (history_api) {
        var toGoBack = document.referrer;
        history.pushState(null, '', '#/b');
    }
```

by doing so, when the user first visit the page it automatically go to hash #b and when the user click back the modal is trigger, but the process stop on the main page without the hash #b. That little trick made your library work on mobile too.

**Comment by ianrogren** [comment]
That's awesome, glad to hear that worked and that it works for mobile too!  Thanks for sharing your solution!
